// <auto-generated />
namespace PreNat.Database.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class immchanges : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(immchanges));
        
        string IMigrationMetadata.Id
        {
            get { return "202304301523053_immchanges"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
