// <auto-generated />
namespace PreNat.Database.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class gestationalforumu : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(gestationalforumu));
        
        string IMigrationMetadata.Id
        {
            get { return "202305081059498_gestationalforumu"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
